
== Helidon car booking

== Presentation

Proposer deux services d'IA pour une société de location de voiture :

* Un service de chat pour discuter librement avec le service client
* Un service de détection de fraude pour déterminer si un client est un fraudeur.

Pour des raisons de simplicité, il n'y a pas d'interaction avec une base de données, l'application est autonome et peut être utilisée "telle quelle".

== Stack

* Java 22 (Temurin OpenJDK distro)
* Helidon 4.0.7
* Helidon CLI 3.0.4
* Maven 3.9.5
* LangChain4j 0.30.0
* LLM provider (Azure for now)

== Pourquoi cette application

* Quarkus propose une extension langchain4j
* Helidon non
* Découvrir l'utilisation de langchain4j avec CDI

== Large Language Models

pres LLM ?

== Ai Model

Provide to langchain the AiModel we want to use for instance:

[source,subs="verbatim,quotes"]
----
@ApplicationScoped
public class ModelFactory {
    @Produces
    private AzureOpenAiChatModel model;
    @PostConstruct
    private void initModel() {
        model = AzureOpenAiChatModel.builder()
                .apiKey(AZURE_OPENAI_KEY)
                .endpoint(AZURE_OPENAI_ENDPOINT)
                .serviceVersion(AZURE_OPENAI_SERVICE_VERSION)
                .deploymentName(AZURE_OPENAI_DEPLOYMENT_NAME)
                .temperature(AZURE_OPENAI_TEMPERATURE)
                .topP(AZURE_OPENAI_TOP_P)
                .timeout(Duration.ofSeconds(AZURE_OPENAI_TIMEOUT_SECONDS))
                .maxRetries(AZURE_OPENAI_MAX_RETRIES)
                .logRequestsAndResponses(AZURE_OPENAI_LOG_REQUESTS_AND_RESPONSES)
                .build();
    }
}
----

== Ai Service Interface

In order to be able to interact with the LLM, we need to define an AiService

[source,subs="verbatim,quotes"]
----
public interface ChatAiService {
    @SystemMessage("""
        You are a customer support agent of a car rental company named 'Miles of Smiles'.
        Before providing information about booking or canceling a booking, you MUST always check:
        booking number, customer name and surname.
        You should not answer to any request not related to car booking or Miles of Smiles company general information.
        When a customer wants to cancel a booking, you must check his name and the Miles of Smiles cancellation policy first.
        Any cancelation request must comply with cancellation policy both for the delay and the duration.
        Today is {{current_date}}.
        """)
    String chat(String question);
}
----

== Ai Service Factory

We need to create a factory with a producer to allow CDI to inject our instance of ChatAiService

[source,subs="verbatim,quotes"]
----
@ApplicationScoped
public class ChatAiFactory {
    @Inject
    private AzureOpenAiChatModel model;

    @Inject
    @ConfigProperty(name = "chat.memory.max.messages", defaultValue = "10")
    private Integer memoryMaxMessages;

    @Produces
    public ChatAiService getChatAiService() {
        return AiServices.builder(ChatAiService.class)
                .chatLanguageModel(model)
                .tools(bookingService)
                .chatMemory(MessageWindowChatMemory.withMaxMessages(memoryMaxMessages))
                .contentRetriever(retriever)
                .build();
    }
}
----

